### ISSUE TITLE
ER Model Design

### ISSUE THREAD

**Issue by kidkkr** [kidkkr/blogkkr#1]
요구사항에 맞추어 ER Diagram 그리기
Diagram 그림 파일 생성
(이슈 게시가 처음이라 실수가 좀 있었습니다;;)

**Comment by rokoroku** [comment]
실수하셔도 Revert가 가능하니 걱정 마시고, 
GitHub 사용을 연습해보신다는 생각으로 이것저것 다양하게 사용해보세요 :)

**Comment by kidkkr** [comment]
헉… 넵 온라인이셨군요ㅎㅎ. 알겠습니다.

**Comment by rokoroku** [comment]
@kidkkr 
팁: GitHub에서는 commit message 또는 PR description에 `closes #1` 등의 키워드를 입력하시면, 관련 issue 함께 close되는 기능이 있어요.

 https://help.github.com/articles/closing-issues-using-keywords/
