### ISSUE TITLE
[database-design] Fix DB table 

### ISSUE THREAD

**Issue by kidkkr** [kidkkr/blogkkr#25]
REST API 작성 중 데이터베이스에 잘못된 점 발견
* username은 unique 해야 하므로 primary key로 추가합니다
* post 삭제시 comment가 cascading하게 삭제되려면, `comments.postId` (FK) 추가해야합니다
* comment 삭제시 자식 comment가 삭제되려면 parentId가 필요합니다
이런 대댓글은 `comments.parentId`(FK) 로 추적합니다

`posts.comments`의 array로 두었던 컬럼을 지우고,
`comments.postId` FK로 posts를 참조하는 것으로 수정 (Nullable)
`comments.parentId` FK로 comments를 참조하는 것으로 수정 (Nullable)

- [x] Add `users.username` constraint as primary key
- [x] Delete column `posts.comments`
- [x] Add column `comments.postId` FK on delete cascade
- [x] Add column `comments.parentId` FK on delete cascade

**Comment by rokoroku** [comment]
@kidkkr 
대댓글은 사실 `comments.commentId` column을 추가하는 것만으로도 구현 가능합니다.
(이 경우, `commentId`는  parent comment를 FK로 가지게 되겠죠?)

물론, 대댓글의 maximum depth에 대한 고려가 되어 있지는 않지만.. 추가 데이터를 가지기 위해선 그를 위한 column도 당연히 필요해지겠죠?

**Comment by kidkkr** [comment]
@rokoroku 네, parent type 컬럼을 둘까 생각해보기도 했었는데,
FK이다 보니 어쩔 수 없이 무조건 컬럼을 하나 더 갖는 수 밖에 없겠군요. 
조언 감사합니다 😄

**Comment by kidkkr** [comment]
- [ ] Add images.postId FK constraint
- [ ] Add images.userId FK constraint

글 삭제시 image를 다루기 위해서 image에도 FK가 필요

**Comment by kidkkr** [comment]
`users.username` UNIQUE  constraint 추가

**Comment by kidkkr** [comment]
커밋메시지를 포함시켰는데도 자동으로(?) close가 안되네요. Closed

**Comment by rokoroku** [comment]
@kidkkr 음.. "fixed #.." 식으로 순서를 맞게 작성하셔야 될 것 같네요.
