### ISSUE TITLE
Change Type Definition 

### ISSUE THREAD

**Issue by kidkkr** [kidkkr/blogkkr#27]
tsc build error
```
src/server.ts(10,31): error TS2304: Cannot find name '__dirname'.
npm ERR! code ELIFECYCLE
```

\+
typings에서 https://www.npmjs.com/~types 로 변경
origin/react-ui 에서 node-server, project-setting 으로 merge후
project setting에서 작업

**Comment by rokoroku** [comment]
`node`의 type definition이 제대로 인식되지 않는 것 같습니다.

현재 사용하고 계신 typings는 deprecated된 type manager로, node나 react, hapi 모두 오래된 버전의 definition 파일들을 이용하고 계시네요. 

지금은 `@types/node`, `@types/react`등 `@types` npm organization을 통해 타입을 설치하여 이용합니다 :)

**Comment by kidkkr** [comment]
https://www.npmjs.com/~types 로 프로젝트 설정을 변경하겠습니다
